### PR TITLE
add link to pyfuse3 porting hints ticket

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@hugovk hmm, strange, all tests run twice.

i edited the readme via the gh web ui and made a PR from there.

**Comment by hugovk** [comment]
Yep: one for pushing the commits, the other for creating the PR.

Travis CI and GitHub Actions both do builds for both push and PR.

For example, if you push a commit from your fork (and assuming you have CIs enabled for your fork), you get a single build for the push.

Then when you create a PR for this repo, you get a single build for the PR.


It's possible to adjust the settings, but I find these generally work well. I always want to test my own work on the CI *before* I create a PR on a repo and be surprised by a fail.

**Comment by hugovk** [comment]
For example, https://github.com/python-llfuse/python-llfuse/pull/51 only has the PR builds.

**Comment by ThomasWaldmann** [comment]
Oh, i didn't notice it created a branch here. Had assumed the PR branch is under my user.

**Comment by hugovk** [comment]
Ah yes, if you have write access to the repo the web UI creates a branch in the repo, rather than your own fork.

**Pull request merged**
