### PR TITLE
some updates for release process, docs, testing

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@Nikratio if you like, please review.

**Comment by ThomasWaldmann** [comment]
After this is merged, even the sdist upload using the old/current method should work, I guess.

**Comment by Nikratio** [comment]
Yes, upload has worked now. Thanks!

**Comment by ThomasWaldmann** [comment]
@Nikratio thanks, that was quick! :-)

Can you upload the tar.gz and your signature there and publish it? I already updated the git tag to point to the new changeset.

https://github.com/python-llfuse/python-llfuse/releases/tag/untagged-17632ef1a622aad81e61

**Comment by Nikratio** [comment]
Is this still needed? I already re-packaged 1.3.7 as tar.gz and uploaded it.

**Comment by ThomasWaldmann** [comment]
It's just to have it on github. It's nice to have it there also in addition to pypi.

You had uploaded the first try (.tar.bz2) there already, but I deleted it as it was superceded by different code in the newer release.

**Comment by Nikratio** [comment]
I have just invited you as a PyPi collaborator. Could you take care of the new release?

Similarly, if you don't get a response from me for merge requests within a few days, please feel free to just merge them.

The key that I've been using is my private key, so I think it's best if you sign the release with yours. If you want, I can provide a signed message somewhere that explains that nothing nefarious is going on.

**Comment by ThomasWaldmann** [comment]
OK, thanks! I'll try to help.

**Pull request merged**
