### PR TITLE
release 1.4.2

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@Nikratio is it correct to just remove "nonempty" there (see commits)?

having it there broke the tests on all python version.

**Comment by ThomasWaldmann** [comment]
@Nikratio did you see my question? Guess the answer is yes, but you for sure know best. :-)

**Comment by Nikratio** [comment]
There has been no changes in libfuse 2.x with respect to `nonempty`, so there should be no need for any changes in llfuse either.

**Comment by ThomasWaldmann** [comment]
@Nikratio this was the test failure:
```
_________________________________ test_lltest __________________________________
Traceback (most recent call last):
  File "/home/runner/work/python-llfuse/python-llfuse/test/test_examples.py", line 49, in test_lltest
    wait_for_mount(mount_process, mnt_dir)
  File "/home/runner/work/python-llfuse/python-llfuse/test/util.py", line 94, in wait_for_mount
    pytest.fail('file system process terminated prematurely')
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/outcomes.py", line 196, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: file system process terminated prematurely
----------------------------- Captured stderr call -----------------------------
fusermount: unknown option 'nonempty'
Traceback (most recent call last):
  File "/home/runner/work/python-llfuse/python-llfuse/test/../examples/lltest.py", line 155, in <module>
    main()
  File "/home/runner/work/python-llfuse/python-llfuse/test/../examples/lltest.py", line 144, in main
    llfuse.init(testfs, options.mountpoint, fuse_options)
  File "src/fuse_api.pxi", line 246, in llfuse.init
Error:     raise RuntimeError('fuse_mount failed')
RuntimeError: fuse_mount failed
```

**Comment by Nikratio** [comment]
Maybe the test environment was updated and someone has copied fusermount3 over fusermount?

**Comment by ThomasWaldmann** [comment]
On Ubuntu 20.04 `fusermount3` **and** `fusermount` are provided by `fuse3` package:

https://packages.ubuntu.com/focal/amd64/fuse3/filelist

**Pull request merged**
